service: my-serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0dc9339dfde009b1f
    subnetIds:
      - subnet-0740ee6eadd2f5a1a
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds-db:connect
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - execute-api:Invoke
      Resource: "*"

functions:
  initializeDB:
    handler: initializeDB.handler
    description: Initialize database with seed data
    timeout: 30
    events:
      - http:
          path: /initializeDB
          method: get
  alltransaction:
    handler: alltransaction.handler
    description: Fetch all transactions
    timeout: 30
    events:
      - http:
          path: /alltransactions
          method: get
  getStatistics:
    handler: getStatistics.handler
    description: Fetch statistics
    timeout: 30
    events:
      - http:
          path: /statistics
          method: get
  getBarChart:
    handler: getBarChart.handler
    description: Fetch BarChart
    timeout: 30
    events:
      - http:
          path: /barchart
          method: get
  getPieChart:
    handler: getPieChart.handler
    description: Fetch PieChart
    timeout: 30
    events:
      - http:
          path: /piechart
          method: get
  combinedData:
    handler: combinedData.handler
    description: Fetch Combined Data
    timeout: 30
    events:
      - http:
          path: /combined-data
          method: get
